/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wazaa;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import FiveCodMover.FiveCodMoverJFrame;
import com.formdev.flatlaf.*;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.LookAndFeel;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author mainpc
 */
public class Jframe extends javax.swing.JFrame {

    /**
     * Creates new form Jframe
     */
    public Jframe() {
        
        con.connect();
        lookaf();
        initComponents();
        comboxTema.setSelectedIndex(4);
        textf1.requestFocus();
    }
    
    Connect con = new Connect();
    
    public static void lookaf(){
    
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
            
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
    }
    
    public static void lookaf(String cn){
    
        try {
            UIManager.setLookAndFeel(cn);
            
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
    }
    
    public static void lookaf(LookAndFeel clas){
    
        try {
            UIManager.setLookAndFeel(clas);
            
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnX = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        comboxOp = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JToggleButton();
        txtAR = new javax.swing.JTextField();
        comboxTema = new javax.swing.JComboBox<>();
        textf1 = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        textf2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnhis = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnX.setText("X");
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test");
        setResizable(false);

        mainPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mainPanelMouseDragged(evt);
            }
        });
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainPanelMousePressed(evt);
            }
        });

        comboxOp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicacion", "Division" }));
        comboxOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxOpActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtAR.setEditable(false);
        txtAR.setText("Resultado");

        comboxTema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nimbus", "Windows", "Windows Classic", "Flat Light", "Flat Dark" }));
        comboxTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxTemaActionPerformed(evt);
            }
        });

        textf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textf1ActionPerformed(evt);
            }
        });
        textf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textf1KeyTyped(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        textf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textf2KeyTyped(evt);
            }
        });

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Test");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnhis.setText("Historial");
        btnhis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(comboxOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcular))
                    .addComponent(textf2)
                    .addComponent(textf1)
                    .addComponent(txtAR, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboxTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnhis)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboxTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboxOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnhis))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMousePressed
        
    }//GEN-LAST:event_mainPanelMousePressed

    private void mainPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseDragged
        
    }//GEN-LAST:event_mainPanelMouseDragged

    private void textf2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textf2KeyTyped

        char num = evt.getKeyChar();
        if (num != '1' && num != '2' && num != '3' && num != '4' && num != '5' &&
            num != '6' && num != '7' && num != '9' && num != '8' && num != '0'){
            evt.consume();
        }
    }//GEN-LAST:event_textf2KeyTyped

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        textf1.setText("");
        textf2.setText("");
        txtAR.setText("Resultado");

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void textf1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textf1KeyTyped

        char num = evt.getKeyChar();
        if (num != '1' && num != '2' && num != '3' && num != '4' && num != '5' &&
            num != '6' && num != '7' && num != '9' && num != '8' && num != '0'){
            evt.consume();
        }
    }//GEN-LAST:event_textf1KeyTyped
    
    private static int temaID;
    
    public static int getTemaID(){
        return temaID;
    }
    
    private void comboxTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxTemaActionPerformed

        String cntema = "";
        
        temaID = comboxTema.getSelectedIndex();
        
        if (comboxTema.getSelectedIndex() == 0) cntema = "javax.swing.plaf.nimbus.NimbusLookAndFeel";
        if (comboxTema.getSelectedIndex() == 1) cntema = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
        if (comboxTema.getSelectedIndex() == 2) cntema = "com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel";
        if (comboxTema.getSelectedIndex() == 3) lookaf(new FlatLightLaf());
        if (comboxTema.getSelectedIndex() == 4) lookaf(new FlatDarkLaf());

        // maintema = cntema;

        if (cntema.equals("")){} else {
            try{
                lookaf(cntema);
            } catch(Exception e){
                System.out.println(e);
            }
        }
        
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_comboxTemaActionPerformed

    private void subir(){
        
        String op = "";
        
        switch (comboxOp.getSelectedIndex()){
            
            case 0 -> op = " +" ;
            case 1 -> op = " - ";
            case 2 -> op = " * ";
            case 3 -> op = " / ";
        }
        
        String sentencia = textf1.getText() + op + textf2.getText() + " = " + txtAR.getText();
        
        con.insertdos(sentencia);
    }
    
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        if (textf1.getText().equals("") || textf2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");

        } else {

            double num1 = Double.parseDouble(textf1.getText());
            double num2 = Double.parseDouble(textf2.getText());
            double result = 0;

            if (comboxOp.getSelectedIndex() == 0 ) result = num1 + num2;
            if (comboxOp.getSelectedIndex() == 1 ) result = num1 - num2;
            if (comboxOp.getSelectedIndex() == 2 ) result = num1 * num2;
            if (comboxOp.getSelectedIndex() == 3 ) result = num1 / num2;

            txtAR.setText(Double.toString(result));
            
            subir();
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void comboxOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxOpActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnXActionPerformed

    private void textf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textf1ActionPerformed
        
    }//GEN-LAST:event_textf1ActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        FiveCodMoverJFrame.MousePressed(evt);
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.setState(Jframe.ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void btnhisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhisActionPerformed

        con.selectAll();
    }//GEN-LAST:event_btnhisActionPerformed
    
    public static String tema;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        lookaf();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnhis;
    private javax.swing.JComboBox<String> comboxOp;
    private javax.swing.JComboBox<String> comboxTema;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField textf1;
    private javax.swing.JTextField textf2;
    private javax.swing.JTextField txtAR;
    // End of variables declaration//GEN-END:variables
}
